[[redirects]]
from = "/*"
to = "/index.html"
status = 200


[[headers]]
  for = "/WebVersion.mp4"
  [headers.values]
    Content-Type = "video/mp4"

[[headers]]
  for = "/MobileVersion.mp4"
  [headers.values]
    Content-Type = "video/mp4"
